import {IModuleData} from '../../models/data.types'

export const columns: IModuleData[] = [
  {
    name: 'Profile Image',
    accessor: 'profilePicture',
    attr: 'profilePicture',
    type: 'image',
    mode: 'image',
    required: false,
    showInTable: true,
  },
  {
    name: 'Name',
    accessor: 'name',
    attr: 'name',
    type: 'text',
    required: true,
    showInTable: true,
  },
  {
    name: 'Email',
    accessor: 'email',
    attr: 'email',
    type: 'email',
    required: true,
    showInTable: true,
  },
  {
    name: 'Role',
    accessor: 'role.name',
    attr: 'roleId',
    mode: 'highlighted',
    type: 'select',
    options: [],
    required: true,
    showInTable: true,
  },
  {
    name: 'Password',
    accessor: 'password',
    attr: 'password',
    type: 'password',
    required: true,
    showInTable: true,
  },
  {
    name: 'Created At',
    accessor: 'createdAt',
    attr: 'createdAt',
    mode: 'labeled',
    type: 'date',
    showInTable: true,
  },
  {
    name: 'Last Updated At',
    accessor: 'updatedAt',
    attr: 'updatedAt',
    mode: 'labeled',
    type: 'date',
    showInTable: true,
  },
]
