// App Types
export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'

// CRUD Types
export const SET_TABLE_DATA = 'SET_TABLE_DATA'
export const SET_TOTAL_RECORDS = 'SET_TOTAL_RECORDS'
export const SET_TABLE_COLUMNS = 'SET_TABLE_COLUMNS'
export const SET_TABLE_NAME = 'SET_TABLE_NAME'
export const SET_IS_TABLE_HAS_FILES = 'SET_IS_TABLE_HAS_FILES'
export const SET_IS_OPERATION_DONE = 'SET_IS_OPERATION_DONE'
export const SET_OPERATIONS_PERMISIIONS = 'SET_OPERATIONS_PERMISIIONS'
export const SET_SELECT_ROW = 'SET_SELECT_ROW'
export const SET_UNSELECT_ROW = 'SET_UNSELECT_ROW'
export const SET_SELECT_ALL_ROWS = 'SET_SELECT_ALL_ROWS'
export const SET_UNSELECT_ALL_ROWS = 'SET_UNSELECT_ALL_ROWS'

// Modal Types
export const OPEN_OPERATION_MODAL = 'OPEN_OPERATION_MODAL'
export const CLOSE_OPERATION_MODAL = 'CLOSE_OPERATION_MODAL'
export const OPEN_CONFIRMATION_MODAL = 'OPEN_CONFIRMATION_MODAL'
export const CLOSE_CONFIRMATION_MODAL = 'CLOSE_CONFIRMATION_MODAL'

export const SET_IS_CONFIRMED = 'SET_IS_CONFIRMED'
export const SET_SELECTED_ID = 'SET_SELECTED_ID'

export const OPEN_UPDATE_MODAL = 'OPEN_UPDATE_MODAL'
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL'
