// App Types
export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'

// CRUD Types
export const SET_TABLE_DATA = 'SET_TABLE_DATA'
export const SET_TABLE_COLUMNS = 'SET_TABLE_COLUMNS'
export const SET_TABLE_NAME = 'SET_TABLE_NAME'
export const SET_IS_TABLE_HAS_FILES = 'SET_IS_TABLE_HAS_FILES'

// Operation Modal Types
export const OPEN_OPERATION_MODAL = 'OPEN_OPERATION_MODAL'
export const CLOSE_OPERATION_MODAL = 'CLOSE_OPERATION_MODAL'
